variables:
    LUA_VERSION: "5.1.4"
    LUA_PATH: "/tmp"
    LUAROCKS_PATH: "/tmp/luarocks"
    LUAROCKS_VERSION: "3.5.0"
    LUACHECK_PATH: $LUAROCKS_PATH/luarocks-$LUAROCKS_VERSION/lua_modules/bin

stages:
    - syntax

.install_lua: &install_lua |-
    export BASE_DIR=$PWD
    yum install -q -y epel-release
    yum install -q -y readline-devel gcc make
    curl https://www.lua.org/ftp/lua-$LUA_VERSION.tar.gz > $LUA_PATH/lua-$LUA_VERSION.tar.gz
    cd $LUA_PATH
    tar -xzf lua-$LUA_VERSION.tar.gz
    cd lua-$LUA_VERSION
    make linux
    make test
    make install INSTALL_TOP=$LUA_PATH
    cd $BASE_DIR

.install_luarocks: &install_luarocks |-
    mkdir -p $LUAROCKS_PATH
    cd $LUAROCKS_PATH
    curl https://luarocks.github.io/luarocks/releases/luarocks-$LUAROCKS_VERSION.tar.gz > luarocks-$LUAROCKS_VERSION.tar.gz
    tar xf luarocks-$LUAROCKS_VERSION.tar.gz
    cd luarocks-$LUAROCKS_VERSION
    ./configure --with-lua-include=$LUA_PATH/lua-$LUA_VERSION/src --with-lua-bin=$LUA_PATH/lua-$LUA_VERSION/src
    make
    make install

.install_luacheck: &install_luacheck |-
    cd $LUAROCKS_PATH/luarocks-$LUAROCKS_VERSION
    luarocks install luacheck


.centos7:
    image: centos:7

.centos7_luac:
    extends: .centos7
    before_script:
        - *install_lua
        - *install_luarocks
        - *install_luacheck
 
.centos7_xmllint:
    extends: .centos7

lua:
    extends: .centos7_luac
    stage: syntax
    
    script:
        - $LUACHECK_PATH/luacheck --config .luacheckrc .

# xml:
#     extends: .centos7_xmllint
#     stage: syntax
#     script:
#         - xmllint --dropdtd GroupCalendar_ImportData.xml
