location: Libs
sources:
  - repo: https://github.com/SamMousa/lua-eventsourcing.git
    name: lua-eventsourcing
    rev:  v0.1.2
    #rev:  master
    type: git
  - repo: https://github.com/lantisnt/LibLogger.git
    name: LibLogger
    rev:  v1.2.0
    type: git
  - repo: https://github.com/lantisnt/lib-st.git
    name: lib-st-4.1.2
    rev:  master
    type: git