location: Libs
sources:
  - repo: https://github.com/SamMousa/lua-eventsourcing.git
    name: lua-eventsourcing
    rev:  v0.1.1
    #rev:  master
    type: git
  - repo: https://github.com/lantisnt/LibLogger.git
    name: LibLogger
    rev:  v1.1.1
    type: git
