name: Alpha Release
on:
  push:

jobs:
  bigwigs_github_alpha_release:
    name: Build via BigWigs packager for GitHub only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gitman
        run: pipx install gitman
      - name: install dependencies
        run: gitman install
      - name: install yq
        run: pipx install yq
      - name: verify required files recursively
        run: scripts/verify-dependencies ClassicLootManager.toc
      - name: Remove git dirs from gitman deps
        run:  find ExternalLibs -type d -name ".git" -execdir rm -rf {} \; -prune
      - name: Copy gitman deps
        run: mkdir -p .release/ClassicLootManager && mv ExternalLibs .release/ClassicLootManager/
      - name: Bigwigs packager
        uses: BigWigsMods/packager@master
        with:
          args: "-o -e -u -m .pkgmeta -g bcc"
      - name: Get name of zip file
        run: echo "artifact=`readlink -f .release/*.zip`" >> $
      - name: Create name of release
        run: echo "releasename=`git describe --abbrev=0 --tags HEAD`-$env:GITHUB_SHA"
      - name: Create Release and upload artifact to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: ${releasename}
          tag: ${releasename}
          artifacts: ${artifact}
          token: ${{ secrets.GITHUB_TOKEN }}