name: Build
on:
  push:
jobs:
  release:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gitman
        run: pipx install gitman
      - name: install dependencies
        run: gitman install
      - name: Bigwigs packager
        uses: BigWigsMods/packager@master
        with:
          args: "-d -e -u"
      - name: List files
        run: tree .release
