name: Lint
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v9.1.0
        with:
          luaVersion: "5.1.4"
      - name: Luacheck Install
        run: |
          echo "##[group]Install luacheck"
          if ! hash luacheck &>/dev/null; then
            sudo apt-get install -yq luarocks 1>/dev/null || exit 1
            sudo luarocks install luacheck 1>/dev/null || exit 1
            sudo luarocks install lanes &>/dev/null || true
          fi
          echo "##[command]luacheck --version"
          luacheck --version
          echo "##[endgroup]"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install pygithub
      - name: luacheck
        run: luacheck -- ClassicLootManager.lua Migration.lua MinimapIcon.lua Utils.lua Alerts/ Integrations/ Global/ Modules/ Locale/ | tee luacheck_report.txt
        continue-on-error: true
      - name: Comment errors
        if: steps.luacheck.outcome != 'success'
        run: python3 ./scripts/comment_lint_errors.py --report luacheck_report.txt
        env:
          GITHUB_COMMENT_TOKEN: ${{ secrets.GITHUB_COMMENT_TOKEN }}
        continue-on-error: true
      - name: Fail on failures
        if: steps.luacheck.outcome != 'success'
        run: exit 1
