name: Test Package
on:
  workflow_dispatch:

jobs:
  packager:
    name: Package via BigWigs packager for DF and WotLK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Bigwigs packager
        uses: BigWigsMods/packager@7cd7fe5fede4ca80f63742e6bc1d777914814380
        with:
          args: "-d -o -u -m .pkgmeta -S"
      - name: Get name of zip file
        run: echo "artifact=`readlink -f .release/*.zip`" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: CLMPackage
          path: .release/${{ env.artifact }}.zip

  discord_announce:
    needs:
      - packager_release
    name: Post a Discord Announcement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install disnake
        run: pip3 install disnake
      - name: announce
        run: python3 scripts/post_release.py $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}