name: wowless
on: 
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/cache@v3
      with:
        path: cache
        key: cache-${{ github.run_id }}
        restore-keys: cache
    - uses: devcontainers/ci@v0.2
      with:
        env: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        imageName: ghcr.io/wowless/wowless-devcontainer
        push: never
        runCmd: git pull && git submodule update --init --depth 1 && lua tools/mkninja.lua && git clone git@github.com:ClassicLootManager/ClassicLootManager.git /clm && cd /clm && git checkout retail && ./scripts/release.sh -S && cd - && bin/run.sh wow --addondir /clm && bin/run.sh wow_classic --addondir /clm && bin/run.sh wow_t --addondir /clm